SportApp/Models/Training.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SportApp.Models
{
    public class Training
    {


        public int Id { get; set; }
        public string? Description { get; set; }// Opis do wyświetlenia przy widoku treningu


        public int PauseBetweenReps { get; set; }//w sekundach int
        public int BreakTimeBetweenEx { get; set; }// w sekundach int
        [ForeignKey("User")]
        public int userId { get; set; }
        
        public virtual User User { get; set; }
        public virtual List<Exercise>? Exercise { get; set; } // lista ćwiczeń

    }
}

SportApp/Controllers/TrainingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportApp.Entities;
using SportApp.Models;
using SportApp.Services;

namespace SportApp.Controllers
{
    [Route("/user/{userId}/training")]
    //[Route("/training/")]
    [ApiController]//wszystkie modele zostały automatycznie zwalidowane dla każdej akcji
    public class TrainingController : Controller
    {

        private readonly SportAppDbContext _context;
        private readonly IMapper _mapper;
        private readonly ITrainingService _trainingService;

        public TrainingController(SportAppDbContext context, IMapper mapper, ITrainingService trainingService)
        {
            _context = context;
            _mapper = mapper;
            _trainingService = trainingService;
        }


        [HttpPost]
        public ActionResult Post([FromRoute] int userId, [FromBody] TrainingDto dto)
        {
            var newTrainingId = _trainingService.Create(userId, dto);
            return Created($"{userId}/training/{newTrainingId}", null);
        }

       
        [HttpGet("list")]
        public async Task<IActionResult> Index()
        {
            return _context.trainings != null ? //jeśli nie jet puste to zwróć widok do którego wysyłasz listę 
                        View(await _context.trainings.ToListAsync()) :
                        Problem("Entity set 'SportAppDbContext.users'  is null.");
        }
        [HttpGet]
        public ActionResult<TrainingDto> Get([FromRoute] int userId)
        {
           // var user = _context.users.FirstOrDefault(u => u.Id == userId);
            var training = _context.trainings.FirstOrDefault(t => t.userId == userId);
            return Ok(training);
        }
        [HttpDelete]
        public ActionResult Delete([FromRoute] int userId)
        {
            var training = _trainingService.GetTrainingById(userId);
            if (training != null)
            _context.trainings.Remove(training);
            _context.SaveChanges();
            return NoContent();
        }







    }
}

SportApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportApp.Entities;
using SportApp.Models;

namespace SportApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly SportAppDbContext _context;
        private readonly IMapper _mapper;

        public UsersController(SportAppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: Users
       // [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = _context
                .users
                .Include(r=> r.Address)
                .Include(r=>r.Training)
                .ToList();
            var userdtos = _mapper.Map<List<UserDto>>(users);

            return _context.users != null ? //jeśli nie jet puste to zwróć widok do którego wysyłasz listę 
                        View(userdtos) :
                        Problem("Entity set 'SportAppDbContext.users'  is null.");
        }

        // GET: Users/Details/5
        //[HttpGet("{id}")]//Popsuło 
        public async Task<IActionResult> Details([FromRoute]int? id)
        {
            
            if (id == null || _context.users == null)
            {
                return NotFound();
            }
            
            var user = await _context
                .users
                .Include(r => r.Address)
                .Include(r => r.Training)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            var userDto= _mapper.Map<UserDto>(user);
            return View(userDto);
        }

        // GET: Users/Create
        public IActionResult Create()//powinien dawać new userDTO i wszystko w nim zebrać a potem zmapować na inne modele
        {

            return View(new CreateUserDto());
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,LastName,Email,City,PostalCode,Street,Country")] CreateUserDto dto)
        {
            var user = _mapper.Map<User>(dto);
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return BadRequest();
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var user = await _context.users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var userDto = _mapper.Map<UpdateUserDto>(user);
            return View(userDto);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Age,LastName,Email,City,PostalCode,Street,Country")] UpdateUserDto dto)//bindujemy te wartości na wartości modelu
        {
            var user = _context.users.FirstOrDefault(user => user.Id == id);
            if (user is null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    if (user.Address is null)
                        user.Address = new Address() { City = dto.City, PostalCode = dto.PostalCode, Street = dto.Street, Country = dto.Country };
                    else 
                    {
                        user.Address.City = dto.City;
                        user.Address.PostalCode = dto.PostalCode;
                        user.Address.Street = dto.Street;
                        user.Address.Country = dto.Country;
                    }
                    user.Age = dto.Age;
                    user.LastName= dto.LastName;
                    user.Email = dto.Email;
                    user.Name = dto.Name;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var user = await _context.users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.users == null)
            {
                return Problem("Entity set 'SportAppDbContext.users'  is null.");
            }
            var user = await _context.users.FindAsync(id);
            if (user != null)
            {
                _context.users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SportApp/Views/Training/Create.cshtml
@model SportApp.Models.TrainingDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Training</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PauseBetweenReps" class="control-label"></label>
                <input asp-for="PauseBetweenReps" class="form-control" />
                <span asp-validation-for="PauseBetweenReps" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreakTimeBetweenEx" class="control-label"></label>
                <input asp-for="BreakTimeBetweenEx" class="form-control" />
                <span asp-validation-for="BreakTimeBetweenEx" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportApp/Views/Training/Index.cshtml
@model IEnumerable<SportApp.Models.Training>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PauseBetweenReps)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BreakTimeBetweenEx)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PauseBetweenReps)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BreakTimeBetweenEx)
            </td>

        </tr>
}                 <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Training" asp-action="Index">Training Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
    </tbody>
</table>